mainFile: router.go

markdownFilesDir: ./wiki

path:
  - ./internal/application/http/router
  - ./internal/application/http/handler
  - ./internal/infrastructure/model
  - ./internal/infrastructure/dao/pagination
  - ./internal/presentation/dto

output: ./assets/docs/

outputTypes:
  - yaml
