// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"nexis.run/nexa-layout/internal/config"
	"nexis.run/nexa-layout/internal/infrastructure/dao"
	"nexis.run/nexa-layout/internal/presentation/service"
)

// Injectors from wire.go:

// Initialize 初始化依赖注入容器
func Initialize(cfg *config.Config) (*Container, error) {
	integration := &Integration{}
	userDao := dao.NewUser()
	diDao := &Dao{
		User: userDao,
	}
	userService := service.NewUser(userDao)
	diService := &Service{
		User: userService,
	}
	container := &Container{
		Config:      cfg,
		Integration: integration,
		Dao:         diDao,
		Service:     diService,
	}
	return container, nil
}
